// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPortfolio.Data;

#nullable disable

namespace MyPortfolio.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260519080905_AddIsGalleryVisible")]
    partial class AddIsGalleryVisible
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ArtworkTag", b =>
                {
                    b.Property<int>("ArtworkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtworkId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArtworkTag");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.Artwork", b =>
                {
                    b.Property<int>("ArtworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGalleryVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("PixivId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ArtworkId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompletionDate");

                    b.HasIndex("PixivId")
                        .IsUnique()
                        .HasFilter("\"PixivId\" IS NOT NULL");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "未分類"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "線稿"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "草圖"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "成圖"
                        });
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.ExternalStat", b =>
                {
                    b.Property<int>("ArtworkId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PixivBookmarks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PixivLikes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PixivViews")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtworkId");

                    b.ToTable("ExternalStats");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            TagName = "正面",
                            Type = 1
                        },
                        new
                        {
                            TagId = 2,
                            TagName = "1/4側面",
                            Type = 1
                        },
                        new
                        {
                            TagId = 3,
                            TagName = "半側面",
                            Type = 1
                        },
                        new
                        {
                            TagId = 4,
                            TagName = "3/4側面",
                            Type = 1
                        },
                        new
                        {
                            TagId = 5,
                            TagName = "正側面",
                            Type = 1
                        });
                });

            modelBuilder.Entity("ArtworkTag", b =>
                {
                    b.HasOne("MyPortfolio.Model.Entities.Artwork", null)
                        .WithMany()
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPortfolio.Model.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.Artwork", b =>
                {
                    b.HasOne("MyPortfolio.Model.Entities.Category", "Category")
                        .WithMany("Artworks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.ExternalStat", b =>
                {
                    b.HasOne("MyPortfolio.Model.Entities.Artwork", "Artwork")
                        .WithOne("ExternalStat")
                        .HasForeignKey("MyPortfolio.Model.Entities.ExternalStat", "ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.Artwork", b =>
                {
                    b.Navigation("ExternalStat");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.Category", b =>
                {
                    b.Navigation("Artworks");
                });
#pragma warning restore 612, 618
        }
    }
}
