// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPortfolio.Model;

#nullable disable

namespace MyPortfolio.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ArtworkTag", b =>
                {
                    b.Property<int>("ArtworkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtworkId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArtworkTag");
                });

            modelBuilder.Entity("JournalEntryJournalTag", b =>
                {
                    b.Property<Guid>("JournalEntriesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JournalTagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("JournalEntriesId", "JournalTagsId");

                    b.HasIndex("JournalTagsId");

                    b.ToTable("JournalEntryJournalTag");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.Artwork", b =>
                {
                    b.Property<int>("ArtworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGalleryVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("PixivId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ArtworkId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompletionDate");

                    b.HasIndex("PixivId")
                        .IsUnique()
                        .HasFilter("\"PixivId\" IS NOT NULL");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "未分類"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "線稿"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "草圖"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "成圖"
                        });
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.ExternalStat", b =>
                {
                    b.Property<int>("ArtworkId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PixivBookmarks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PixivLikes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PixivViews")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtworkId");

                    b.ToTable("ExternalStats");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.JournalImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalFilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("JournalImages");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.JournalTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JournalTags");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            TagName = "正面",
                            Type = 1
                        },
                        new
                        {
                            TagId = 2,
                            TagName = "1/4側面",
                            Type = 1
                        },
                        new
                        {
                            TagId = 3,
                            TagName = "半側面",
                            Type = 1
                        },
                        new
                        {
                            TagId = 4,
                            TagName = "3/4側面",
                            Type = 1
                        },
                        new
                        {
                            TagId = 5,
                            TagName = "正側面",
                            Type = 1
                        });
                });

            modelBuilder.Entity("ArtworkTag", b =>
                {
                    b.HasOne("MyPortfolio.Model.Entities.Artwork", null)
                        .WithMany()
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPortfolio.Model.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JournalEntryJournalTag", b =>
                {
                    b.HasOne("MyPortfolio.Model.Entities.JournalEntry", null)
                        .WithMany()
                        .HasForeignKey("JournalEntriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPortfolio.Model.Entities.JournalTag", null)
                        .WithMany()
                        .HasForeignKey("JournalTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.Artwork", b =>
                {
                    b.HasOne("MyPortfolio.Model.Entities.Category", "Category")
                        .WithMany("Artworks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.ExternalStat", b =>
                {
                    b.HasOne("MyPortfolio.Model.Entities.Artwork", "Artwork")
                        .WithOne("ExternalStat")
                        .HasForeignKey("MyPortfolio.Model.Entities.ExternalStat", "ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.JournalImage", b =>
                {
                    b.HasOne("MyPortfolio.Model.Entities.JournalEntry", "JournalEntry")
                        .WithMany("Images")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.Artwork", b =>
                {
                    b.Navigation("ExternalStat");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.Category", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("MyPortfolio.Model.Entities.JournalEntry", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
